# WELCOME TO BAN-EM's CONFIG!
# IN HERE YOU CAN EDIT THE PLUGIN VIA USING "True" OR "False" Statements!
# OR YOU CAN USE WORDS WHEN ABOVE THE SETTING IT WILL SAY (S) = String!


#(S) - DO NOT USE &colours ATM! As this is not implement!
Noperm: 'YOU DO NOT HAVE THE PERM TO USE THIS!'