# WELCOME TO BAN-EM's CONFIG!
# IN HERE YOU CAN EDIT THE PLUGIN VIA USING "True" OR "False" Statements!
# OR YOU CAN USE WORDS WHEN ABOVE THE SETTING IT WILL SAY (S) = String!
# WARN FEATURE IS NOT WORKING TO FULL STANDORD! THERE MAY BE BUGS!!!!!!!!!

#(S) - DO NOT USE &colours ATM! As this is not implement!
Noperm: 'YOU DO NOT HAVE THE PERM TO USE THIS!'


#(S) - DO NOT USE &colours ATM! As this is not implement!
ReloadMessage: 'You have reloaded BanEm!'






















#DO NOT CHANGE!

#Config VER: 0.5
#Plugin VER: 0.5