# WELCOME TO BAN-EM's CONFIG!
# IN HERE YOU CAN EDIT THE PLUGIN VIA USING "True" OR "False" Statements!
# OR YOU CAN USE WORDS WHEN ABOVE THE SETTING IT WILL SAY (S) = String!
# WARN FEATURE IS NOT WORKING TO FULL STANDORD! THERE MAY BE BUGS!!!!!!!!!
# USE & CHAT COLORS IN STRINGS!

#(S)
Noperm: '&cYOU DO NOT HAVE THE PERM TO USE THIS!'


#(S)
ReloadMessage: '&cYou have reloaded BanEm!'

#(S)
KickReason:  '&cYou have been kicked!'





















#DO NOT CHANGE!

#Config VER: 0.7
#Plugin VER: 0.7