# WELCOME TO BAN-EM's CONFIG!
# IN HERE YOU CAN EDIT THE PLUGIN VIA USING "True" OR "False" Statements!
# OR YOU CAN USE WORDS WHEN ABOVE THE SETTING IT WILL SAY (S) = String!
# USE & CHAT COLORS IN STRINGS!

#(S)
Noperm: '&cYOU DO NOT HAVE THE PERM TO USE THIS!'

#(S)
ReloadMessage: '&cYou have reloaded BanEm!'

#(S)
KickReason:  '&cYou have been kicked!'

#(S) - You can not use & in this!
BanReason: 'You have been struck down by Ban-EM'



